version: '3'

volumes:
  postgres_data:
    driver: local
  mongo_data:
  neo4j_data:
  neo4j_plugins:

services:
  neo4j:
    image: neo4j
    volumes:
      - neo4j_data:/data
      - neo4j_plugins:/plugins
    restart: always
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - '7474:7474'
      - '7687:7687'

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: testkeycloakdb
      POSTGRES_USER: testkeycloakuser
      POSTGRES_PASSWORD: testkeycloakpassword
    ports:
      - '5432:5432'
    restart:
      always

  keycloak:
    image: quay.io/keycloak/keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: testkeycloakdb
      KC_DB_PASSWORD: testkeycloakpassword
      KC_DB_USERNAME: testkeycloakuser
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - '8081:8080'
    depends_on:
      - postgres
    restart:
      always